/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/table/components/actions/index.vue')['default']
    AsyncSelect: typeof import('./src/components/async-select/index.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BadgeWithTooltip: typeof import('./src/components/BadgeWithTooltip.vue')['default']
    BooleanSelect: typeof import('./src/components/boolean-select.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DebouncedSearch: typeof import('./src/components/DebouncedSearch.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Filter: typeof import('./src/components/filter/index.vue')['default']
    FlagsSelect: typeof import('./src/components/flags-select/index.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LastMajorTag: typeof import('./src/components/LastMajorTag.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MetaViewDialog: typeof import('./src/components/MetaViewDialog.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    QaReportViewDialog: typeof import('./src/components/QaReportViewDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/table/index.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
  }
}
